[package]
name = "universal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
thiserror = "2"
educe = "0.6"
validator = { version = "0.20.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
colored = "3"